### PR TITLE
Change package name from gecos-agent to gecosws-agent and version for…

### PR DESCRIPTION
**Pull request by System25**
…mat to X.YgecosZ

### CODE REVIEW

**Comment by alfem** [comment]
If you change the package name the new autoupdate mechanism must point to the new name.

https://github.com/gecos-team/gecosws-agent/blob/xenial/scripts/gecos-chef-client-wrapper#L58

**Comment by System25** [comment]
> If you change the package name the new autoupdate mechanism must point to the new name.
> 
> https://github.com/gecos-team/gecosws-agent/blob/xenial/scripts/gecos-chef-client-wrapper#L58

Oh, you are right. 
Now it must be fixed.

Best regards!

**Comment by alfem** [comment]
Ok for this package, but gecosws-meta also must be updated: https://github.com/gecos-team/gecosws-meta/blob/xenial/gcs/depends#L18

**Comment by System25** [comment]
Yes, I will update it later.
Thanks

**Pull request merged**
